###

POST http://localhost:5000/api/transporte HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NGEwMjZkNTc3OTJhNDZhYzlkODQxZCIsIm5vbWJyZSI6ImVkd2luIiwiYXBlbGxpZG8iOiJtYXJpbiIsInJvbGVzIjpbImFkbWluaXN0cmFkb3IiXSwiaWF0IjoxNzQ5NjgwODAzLCJleHAiOjE3NDk3MjQwMDN9.Wmz2TFWkwYW5PuKM8ft1d8iSLrbklGmhMriULaB8ScI

  
  {
    "nombre": "TransCordillera",
    "capacidad": 42,
    "descripcion": "Bus interdepartamental con cortinas, aire y asientos tipo cama.",
    "comodidades": ["Baño", "Asientos Cama"],
    "placa": "VWX-5566",
    "categoria": "Bus XL"
  }



###

GET http://localhost:5000/api/transporte HTTP/1.1

###

GET http://localhost:5000/api/transporte/6759182fc767cadc68d97c04 HTTP/1.1

###

DELETE http://localhost:5000/api/transporte/6759182fc767cadc68d97c04 HTTP/1.1
